### ISSUE TITLE
[Bug]: bt-mqtt-gateway woun't start.

### ISSUE THREAD

**Issue by jensenbln** [FaserF/hassio-addons#102]
### The problem

bt-mqtt-gateway woun't start.

### What version of Home Assistant Core has the issue?

core-2022.12.3

### What version of the addon has the issue?

1.1.1

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

BT-MQTT-Gateway

### Log information

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Found config file at /share/bt-mqtt-gateway.yaml . Copying it now.
Starting bt-mqtt-gateway in normal mode
Huge thanks to @zewelor who is the creator of bt-mqtt-gateway - https://github.com/zewelor/bt-mqtt-gateway
If there are any bugs occurring below this line, please report it to the bt-mqtt-gateway developer and not to @FaserF - thanks.
Traceback (most recent call last):
  File "/application/./gateway.py", line 63, in <module>
    from config import settings
  File "/application/config.py", line 5, in <module>
    settings = yaml.safe_load(f)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.10/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/application/config.yaml", line 29, column 41
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

environment: 

arch: amd64
audio_input: None
audio_output: None
boot: true
image: ghcr.io/home-assistant/qemux86-64-homeassistant
ip_address: 172.30.32.1
machine: qemux86-64
port: 8123
ssl: false
update_available: false
version: 2022.12.3
version_latest: 2022.12.3
watchdog: true

**Comment by FaserF** [comment]
Please check your config.yaml file . The log file from the program says that there is a error within your yaml file:

`yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/application/config.yaml", line 29, column 41`

From the addon side everything is working.

**Comment by jensenbln** [comment]
oh thanks, yes, indeed. but now i get this message:

18:41:24 Starting
18:41:24 Adding 4 thermostat devices
18:41:24 Updating 4 thermostat devices
18:41:24 Error during update of thermostat device 'wz' (00:1A:22:06:9F:C9): BTLEDisconnectError
18:41:24 Error during update of thermostat device 'kz' (00:1A:22:06:9F:D4): BTLEDisconnectError
18:41:24 Error during update of thermostat device 'sz' (00:1A:22:06:43:5E): BTLEDisconnectError
18:41:24 Error during update of thermostat device 'bedroom' (00:1A:22:06:43:B2): BTLEDisconnectError

**Comment by FaserF** [comment]
Thats most often a issue with bad bluetooth connections.
I recommend searching the issues at the developer of bt-mqtt-gateway for similar people and issues:
https://github.com/zewelor/bt-mqtt-gateway

I am only providing the homeassistant addon, not the software itself.
