### ISSUE TITLE
[Bug]:  bt-mqtt-gateway does not work anymore after update to 1.4.0

### ISSUE THREAD

**Issue by Micha70** [FaserF/hassio-addons#263]
### The problem

After update to 1.4.0 addon will be stopped after a few seconds.

### What version of Home Assistant Core has the issue?

 Core 2024.1.6 // Supervisor 2023.12.1 // Operating System Frontend 20240104.0

### What version of the addon has the issue?

1.4.0

### What type of installation are you running?

Home Assistant Supervised

### Add-On causing the issue

BT-MQTT-Gateway

### Log information

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Found config file at /share/bt-mqtt-gateway.yaml . Copying it now.
/start.sh: line 19: ./venv/bin/activate: No such file or directory
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped_
```

### Additional information

Last running version was 1.3.8.

**Comment by Micha70** [comment]
This is protocoll if I use version 1.3.8:

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Found config file at /share/bt-mqtt-gateway.yaml . Copying it now.
Starting bt-mqtt-gateway in normal mode
Huge thanks to @zewelor who is the creator of bt-mqtt-gateway - https://github.com/zewelor/bt-mqtt-gateway
If there are any bugs occurring below this line, please report it to the bt-mqtt-gateway developer and not to @FaserF - thanks.
16:54:16 Starting
16:54:16 Adding 2 thermostat devices
16:54:16 Updating 2 thermostat devices
```

**Comment by TJuTZu** [comment]
Yes, it installed now properly and works just fine.

**Comment by FaserF** [comment]
With version 1.4.1 the addon should now install successfully again. Homeassistant developers did some python adjustments, that I needded to make compatible with this addon.

For me the gateway throws some errors after starting, but this is nothing from my addon. Since I am not using the gateway anymore, please let me know if yours are working fine again.

**Comment by Micha70** [comment]
@FaserF unfortunately still not working. It's now a step ahead, but generates now a new problem....

```s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Found config file at /share/bt-mqtt-gateway.yaml . Copying it now.
Huge thanks to @zewelor who is the creator of bt-mqtt-gateway - https://github.com/zewelor/bt-mqtt-gateway
If there are any bugs occurring below this line, please report it to the bt-mqtt-gateway developer and not to @FaserF - thanks.
Starting bt-mqtt-gateway in normal mode
18:51:17 Starting
Exception ignored in: <function Client.__del__ at 0x7fa80c2f20>
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
           ^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "/application/./gateway.py", line 81, in <module>
    mqtt = MqttClient(settings["mqtt"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/application/mqtt.py", line 14, in __init__
    self._mqttc = mqtt.Client(
                  ^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'
Exception ignored in: <function MqttClient.__del__ at 0x7fa80d67a0>
Traceback (most recent call last):
  File "/application/mqtt.py", line 138, in __del__
    self.publish(
  File "/application/mqtt.py", line 47, in publish
    self.mqttc.publish(topic, m.payload, retain=m.retain)
    ^^^^^^^^^^
  File "/application/mqtt.py", line 110, in mqttc
    return self._mqttc
           ^^^^^^^^^^^
AttributeError: 'MqttClient' object has no attribute '_mqttc'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

I think I need to address now to @zewelor....

**Comment by Micha70** [comment]
Seem's there is no support anymore by @zewelor. Repository on archived state. No issues can be created. Means I will stay wit version 1.3.8...

**Comment by Micha70** [comment]
With 1.4.1 the problem the issue is still not solved. But seems more to be a problem of the original  https://github.com/zewelor/bt-mqtt-gateway .... Which is not supported anymore.

**Comment by Micha70** [comment]
During update to 1.4.2 I get the following error:

_The command '/bin/ash -o pipefail -c source ./venv/bin/activate && cd /application && apk add --no-cache py3-pip && pip install --no-cache-dir -r ./requirements.txt && pip install --no-cache-dir `./gateway.py -r all`' returned a non-zero code: 1_

Means the update is not working...

**Comment by FaserF** [comment]
Unfortunatly this is a dependency issue, no issue with the addon itself, which cant be fixed from me. The original dependecy has been deprecated from the developer, therefore it wont be fixed. I recommend switching to bluetooth proxy.
