### ISSUE TITLE
[Feature Request]: Add exif php extension

### ISSUE THREAD

**Issue by ladescamps** [FaserF/hassio-addons#281]
### The request

Add exif php extension

### For which Add-On

Apache2

### Is your feature request related to a problem?

```txt
Hi, thanks a lot for this add-on so usefull.
I miss the exif php extension which is not available in the default addon, could it be possible to add it please ?
Thanks a lot
Laurent
```

**Comment by FaserF** [comment]
Is now available with Apache2 Full Version 2.8.0

**Comment by ladescamps** [comment]
Thanks,   look's like the addon doesn't
      start anymore
    
    
    - restarted HA
    
    - removed personnal httpd.con
    
    - removed personnal
      apache2addon_php.ini
    
    
    addon still does not start 
    
    
    
    - uninstall/install addon, using
      default configuration,  addon still does not start.
    
    
    bellow supervisor logfile : 
    
    
    
    
      2024-05-01 14:17:44.807 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Apache2 is failed, restarting...
2024-05-01 14:17:44.813 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:17:45.187 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:17:48.812 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Apache2 is failed, restarting...
2024-05-01 14:17:48.818 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:17:49.194 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:17:52.836 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-185591' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-05-01 14:18:27.905 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:18:28.269 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:18:31.869 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-185873' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-05-01 14:18:39.050 ERROR (SyncWorker_1) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running
2024-05-01 14:18:59.431 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:18:59.786 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:19:03.412 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-186157' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-05-01 14:19:18.231 ERROR (SyncWorker_2) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running
2024-05-01 14:19:54.737 ERROR (SyncWorker_6) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running
2024-05-01 14:19:57.339 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:19:57.881 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:20:01.531 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-186444' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00



    
    
    
    
    
    
    
    regards
    
    
    Laurent
    
    
    
    
    
    Le 01/05/2024 à 13:42, Fabian Seitz a
      écrit :
    
    
      Is now available with Apache2 Full Version 2.8.0

**Comment by ladescamps** [comment]
Franz
    
    
    after Full HA restart,  no more error message in supervisor log :
      
    
    2024-05-01 14:40:56.323 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:40:57.108 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:41:39.431 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:41:39.784 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0

but addon stil does not start 

Tried "rebuilt"  action, but still fail : 

2024-05-01 14:46:30.559 INFO (MainThread) [supervisor.docker.addon] Build 605cee21/aarch64-addon-apache2:2.8.0 done
2024-05-01 14:46:30.576 INFO (MainThread) [supervisor.addons.addon] Add-on '605cee21_apache2' successfully rebuilt
2024-05-01 14:46:54.286 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:47:02.840 ERROR (SyncWorker_4) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running
2024-05-01 14:47:18.219 ERROR (SyncWorker_4) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running


    
    regards
    
    
    Laurent
    
    
    
    Le 01/05/2024 à 14:34, laurent Descamps
      a écrit :
    
    
      
      Thanks,   look's like the addon
        doesn't start anymore
      
      
      - restarted HA
      
      - removed personnal httpd.con
      
      - removed personnal
        apache2addon_php.ini
      
      
      addon still does not start 
      
      
      
      - uninstall/install addon, using
        default configuration,  addon still does not start.
      
      
      bellow supervisor logfile : 
      
      
      
      
        2024-05-01 14:17:44.807 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Apache2 is failed, restarting...
2024-05-01 14:17:44.813 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:17:45.187 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:17:48.812 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Apache2 is failed, restarting...
2024-05-01 14:17:48.818 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:17:49.194 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:17:52.836 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-185591' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-05-01 14:18:27.905 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:18:28.269 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:18:31.869 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-185873' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-05-01 14:18:39.050 ERROR (SyncWorker_1) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running
2024-05-01 14:18:59.431 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:18:59.786 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:19:03.412 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-186157' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-05-01 14:19:18.231 ERROR (SyncWorker_2) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running
2024-05-01 14:19:54.737 ERROR (SyncWorker_6) [supervisor.docker.manager] Container addon_605cee21_apache2 is not running
2024-05-01 14:19:57.339 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_605cee21_apache2 application
2024-05-01 14:19:57.881 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 605cee21/aarch64-addon-apache2 with version 2.8.0
2024-05-01 14:20:01.531 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-186444' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00



      
      
      
      
      
      
      
      regards
      
      
      Laurent
      
      
      
      
      
      Le 01/05/2024 à 13:42, Fabian Seitz a
        écrit :
      
      
        Is now available with Apache2 Full Version 2.8.0

**Comment by FaserF** [comment]
Sorry, there was an issue with this release and the new PHP8.2 
Please give it another try with Version 2.8.1

**Comment by ladescamps** [comment]
Hi Fabian, it works great ! thanks !
