### ISSUE TITLE
Issue installing Apache AddOn 'non-zero code:2'

### ISSUE THREAD

**Issue by felice-leone** [FaserF/hassio-addons#33]
Hi,

i can't install the Apache AddOn. I always get this error:

> The command '/bin/ash -o pipefail -c apk update && apk upgrade' returned a non-zero code: 2

I have already installed a fresh version of Homeassistant, and first thing i have done is installing the AddOn, but still the same error.

Any ideas? It has worked in the past (must be months ago...)

Thanks for your great work anyways :-)

FL
![error](https://user-images.githubusercontent.com/61671883/126447813-884b01a0-4ce7-4b54-b78a-2fdd164e4697.jpg)

**Comment by FaserF** [comment]
Hi,
unfortunatly I am unable to reproduce the issue, as the installation went fine again on my machine. 
Could you try to install the Apache2 Minimal or the Apache2 Minimal with MariaDB Version and check if the issue is there too?

**Comment by felice-leone** [comment]
Hi,

wow, thanks for the fast response. Same error for the minimal Version.

I am running it on an Raspberry Pi in Supervised mode, if this does matter...

Really strange, i had running it some month ago on the same Hardware. The SD Card failed so i reinstalled on a new one, but this time your AddOn refuses to install...
![error](https://user-images.githubusercontent.com/61671883/126450578-c17e82af-b4e4-42f4-a071-029c7ff29188.jpg)

By luck i have an old screenshot (can't remove the red mark, sorry), where you can see the blue line above your AddOn...

![noerror](https://user-images.githubusercontent.com/61671883/126451521-87ecc4b3-cad3-4438-9022-c2596f233459.jpg)

Is this any helpfull?

Thanky again

FL

**Comment by FaserF** [comment]
I have updated my Dockerfiles with 5bcab18 and removed the line that caused your issues. 
I still dont get why you get an error message, as the command is correct, but it is not needed. 
Please give it now another try. I have not bumped the version, so you will still see Version 2.1.0

**Comment by felice-leone** [comment]
Hi, thanks a lot for your efforts. I gave it a test, and something changed, even if it does still not install:

> The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 6

![error](https://user-images.githubusercontent.com/61671883/126479389-b2299a21-5cbe-4a86-a5b1-9fcb8a01f2dd.jpg)

**Comment by FaserF** [comment]
Hmm, got the same issue right now while testing a new update of another of my addons. Went away after deleting the local files and pasting it back in again which is no solution for addons from a git repo.
Please restart the full server and give it another try then, as the commands are correct and working here, it looks like a temporary issue by the HA Supervisor.

**Comment by felice-leone** [comment]
Hi,

> Please restart the full server and give it another try then

Done. Same result.
`The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 6`

**Comment by derhappy** [comment]
Wanted to try you Add-On too, but I got the same message. Running a Raspi 4, supervised core-2021.8.5.

The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 6

**Comment by FaserF** [comment]
Could both of you go to your HA Info page (/config/info) and send over me the system health informations?
![image](https://user-images.githubusercontent.com/12374134/129708095-49420785-b838-4f8a-9415-fa63a608cf2b.png)

I am interested in seeing your hardware architecture

**Comment by derhappy** [comment]
Here we go:

## System Health

version | core-2021.8.6
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.52-v7l+
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 927
Installed Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.8
disk_total | 219.8 GB
disk_used | 30.5 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | ADB - Android Debug Bridge (0.8.0), AppDaemon 4 (0.6.2), Check Home Assistant configuration (3.8.0), File editor (5.3.3), Nginx Proxy Manager (0.11.0), Simple Scheduler (0.30.05), Terminal & SSH (9.1.3), chrony (2.2.0), Pi-hole (DEPRECATED!) (4.1.2), MariaDB (2.4.0), Mosquitto broker (6.0.1), Frigate NVR (1.13)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 7
views | 20
mode | storage

</details>

**Comment by jcerullo** [comment]
System Health
| Version | core-2021.7.4 |
| Installation Type | Home Assistant OS |
| Development | false |
| Supervisor | true |
| Docker | true |
| Virtual Environment | false |
| Python Version | 3.9.5 |
| Operating System Family | Linux |
| Operating System Version | 5.10.17-v7 |
| CPU Architecture | armv7l |
| Timezone | America/New_York |



    On Tuesday, August 17, 2021, 06:14:14 AM EDT, Fabian Seitz ***@***.***> wrote:  
 
 


Could both of you go to your HA Info page (/config/info) and send over me the system health informations?


I am interested in seeing your hardware architecture

**Comment by FaserF** [comment]
Thank you all for your feedback and system informations.

Do you use any other custom (not official) addon? If yes, could you try to uninstall that addon and try reinstalling it?

If you get a similar issue there, it is no issue with my addon, maybe then as @foobarjimmy says a network issue.
I am very sorry but I am unable to reproduce it with my instance and my test instance.

**Comment by jcerullo** [comment]
Nothing in current use.  Sorry.
    On Thursday, September 2, 2021, 04:41:35 AM EDT, Fabian Seitz ***@***.***> wrote:  
 
 


Thank you all for your feedback and system informations.

Do you use any other custom (not official) addon? If yes, could you try to uninstall that addon and try reinstalling it?

If you get a similar issue there, it is no issue with my addon, maybe then as @foobarjimmy says a network issue.
I am very sorry but I am unable to reproduce it with my instance and my test instance.

**Comment by FaserF** [comment]
Seems really to be some kind of network issue, where I cant help:
https://stackoverflow.com/questions/56855928/bin-sh-c-apk-no-cache-returned-non-zero-code-4 

@bilalui now got the same issue, maybe he will discover something.

If you are using adguard or some kind of that stuff, be sure to whitelist the alpine URLS
dl-cdn.alpinelinux.org

**Comment by FaserF** [comment]
@felice-leone Are you also running Homeassistant Supervised and not the Homeassistant OS?

Thats the only thing that seems to be the same between @felice-leone @bilalui and @derhappy seems to be running HA supervised.

Me and @foobarjimmy seem to run HA as OS and are not having any issues. 
The more I tried to deep into the issue, the more messages I can see, that it has something to do with the network https://github.com/gliderlabs/docker-alpine/issues/334

**Comment by guarddog13** [comment]
I am running home assistant os and can't get this addon to install with the above errors

**Comment by FaserF** [comment]
Thanks for the feedback. Can you give me details about your setup?
Maybe the rest from this post here could answer their details too

- what device
- What DNS server are you using (Internet provider, google, cloudflare, PiHole, Adguard?)
- What Homeassistant OS version
- Your country

**Comment by guarddog13** [comment]
It was NORDVPN just for the HAAS, forgot to change this with adguard the other day. It's installed now.

**Comment by kekegt** [comment]
Hi! I have the same error updating from 2.4.1 to 2.4.2.

what device (hardware)
Generic x86-64

What DNS server are you using (Internet provider, google, cloudflare, PiHole, Adguard?)
Adguard (Tried with protection off also)
Google DNS when protection is off

Any VPN used?
Nope

What Homeassistant OS version
2022.8.0

Your country
Canada

Here is the error:
----------------------------------------------------------------------
```
Logger: homeassistant.core
Source: components/hassio/update.py:169
First occurred: 9:06:34 PM (3 occurrences)
Last logged: 9:22:43 PM

Error executing service: <ServiceCall update.install (c:01G9K65RN90GR2YMKR8EB3TNNF): entity_id=['update.apache2_update'], backup=True>
Error executing service: <ServiceCall update.install (c:01G9K6FCT0EBBV6GMXN1P2H5RK): entity_id=['update.apache2_update'], backup=True>
Error executing service: <ServiceCall update.install (c:01G9K73EYSN072VMFW5G6334A4): entity_id=['update.apache2_update'], backup=True>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: The command '/bin/ash -o pipefail -c apk --no-cache add mosquito mosquito-dev' returned a non-zero code: 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Apache2: The command '/bin/ash -o pipefail -c apk --no-cache add mosquito mosquito-dev' returned a non-zero code: 2
```
----------------------------------------------------------------------

**Comment by FaserF** [comment]
A potential solution can be found here: 
https://github.com/FaserF/hassio-addons/issues/127
