### ISSUE TITLE
[Bug]: Home Assistant Community Add-on: Netboot.xyz unable to change webui port

### ISSUE THREAD

**Issue by rysiulg** [FaserF/hassio-addons#341]
### The problem

Yes in config is don't change, but -when other addon uses this port -it can't start -and this port is default used by grafana -very often integrated with HA
After input other port number in startup log there is:
```
Node.js v20.15.1
dnsmasq-dhcp: no address range available for DHCP request via end0
dnsmasq-dhcp: no address range available for DHCP request via end0
dnsmasq-dhcp: no address range available for DHCP request via end0
Invalid port "undefined" in environment variable WEB_APP_PORT. Using default port 3000 instead.
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1898:16)
    at listenInCluster (node:net:1946:12)
    at Server.listen (node:net:2044:7)
    at Object.<anonymous> (/app/app.js:359:6)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1925:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
``` 

### What version of Home Assistant Core has the issue?

2024.10.4

### What version of the addon has the issue?

1.7.3

### What type of installation are you running?

Home Assistant Supervised

### Add-On causing the issue

Netboot-XYZ

### Log information

```txt
at emitErrorNT (node:net:1925:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v20.15.1
dnsmasq-dhcp: no address range available for DHCP request via end0
dnsmasq-dhcp: no address range available for DHCP request via end0
dnsmasq-dhcp: no address range available for DHCP request via end0
Invalid port "undefined" in environment variable WEB_APP_PORT. Using default port 3000 instead.
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1898:16)
    at listenInCluster (node:net:1946:12)
    at Server.listen (node:net:2044:7)
    at Object.<anonymous> (/app/app.js:359:6)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1925:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v20.15.1
dnsmasq-dhcp: no address range available for DHCP request via end0
dnsmasq-dhcp: no address range available for DHCP request via end0
Invalid port "undefined" in environment variable WEB_APP_PORT. Using default port 3000 instead.
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1898:16)
    at listenInCluster (node:net:1946:12)
    at Server.listen (node:net:2044:7)
    at Object.<anonymous> (/app/app.js:359:6)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1925:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v20.15.1
dnsmasq-dhcp: no address range available for DHCP request via end0
dnsmasq-dhcp: no address range available for DHCP request via end0
Invalid port "undefined" in environment variable WEB_APP_PORT. Using default port 3000 instead.
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1898:16)
    at listenInCluster (node:net:1946:12)
    at Server.listen (node:net:2044:7)
    at Object.<anonymous> (/app/app.js:359:6)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1925:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v20.15.1
dnsmasq-dhcp: no address range available for DHCP request via end0
dnsmasq-dhcp: no address range available for DHCP request via end0
```

**Comment by riemers** [comment]
fyi, if i change the webserver port to something else then 85 when it boots up the logs says "port not set, defaulting to 85"

```Nginx port was not set! Setting 85 as default!```

**Comment by FaserF** [comment]
I am currently refactoring all addons and including netboot, which will fix this issue.

Please give it a try, once this PR is merged and a new release has been published #491
