### ISSUE TITLE
Apache2 Version 2.3.0 won't upgrade from 2.2.2

### ISSUE THREAD

**Issue by RogerSelwyn** [FaserF/hassio-addons#72]
**Describe the bug**
I'm trying to upgrade from 2.2.2 to 2.3.0, I'm getting the error shown below in the supervisor logs (also something similar in the HA log).

**To Reproduce**
1. Go to working Apache2 2.2.2
2. Click on Update
3. Update fails
4. See supervisor log

**Expected behavior**
Update completes successfully

**Screenshots**

**What Addon?**
 - Addon Name: Apache2
- Addon Version: 2.2.2 --> 2.3.0

**Additional context**
Supervisor log
```
22-06-07 17:53:12 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build 605cee21/aarch64-addon-apache2:2.3.0: The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 1
22-06-07 17:53:12 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/24 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:12.0.0
Step 2/24 : FROM ${BUILD_FROM}
 ---> eeb199c65a6c
Step 3/24 : ENV LANG C.UTF-8
 ---> Using cache
 ---> c3a103b6ec5b
Step 4/24 : RUN mkdir /run/apache2
 ---> Using cache
 ---> aa794f840d99
Step 5/24 : RUN apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl
 ---> Running in 69a37e47c42c
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:

  php7-apache2 (no such package):
    required by: world[php7-apache2]
Removing intermediate container 69a37e47c42c
```

Core log
```
2022-06-07 17:53:12 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall update.install (c:01G4ZH9JCJT71VQFTAWGMYAD7K): entity_id=['update.apache2_update'], backup=True>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 1
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 1722, in catch_exceptions
await coro_or_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
await entity.async_install_with_progress(version, backup)
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
await self.async_install(version, backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Apache2: The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 1
```

**Comment by homonto** [comment]
same here:
<img width="511" alt="Screenshot 2022-06-08 at 06 47 16" src="https://user-images.githubusercontent.com/46562447/172541352-76eaa1c7-0402-454c-b513-7e00343ff737.png">

**Comment by RogerSelwyn** [comment]
I've just tried 2.4.0. I get the below error:

```
22-06-08 08:43:00 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 605cee21/aarch64-addon-apache2:2.4.0: The command '/bin/ash -o pipefail -c apk --no-cache add php81 php81-dev php81-fpm php81-mysqli php81-opcache php81-gd zlib php81-curl php81-phar php81-mbstring php81-pecl-mcrypt php81-zip php81-pdo php81-pdo_mysql php81-iconv php81-dom php81-session php81-intl php81-soap php81-fileinfo php81-xml php81-ctype' returned a non-zero code: 1
22-06-08 08:43:00 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/24 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:12.0.0
Step 2/24 : FROM ${BUILD_FROM}
 ---> eeb199c65a6c
Step 3/24 : ENV LANG C.UTF-8
 ---> Using cache
 ---> c3a103b6ec5b
Step 4/24 : RUN mkdir /run/apache2
 ---> Using cache
 ---> aa794f840d99
Step 5/24 : RUN apk --no-cache add apache2 php81-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl
 ---> Running in 35a12f7fd1fd
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
(1/29) Installing libuuid (2.38-r1)
(2/29) Installing apr (1.7.0-r2)
(3/29) Installing expat (2.4.8-r0)
(4/29) Installing apr-util (1.6.1-r12)
(5/29) Installing pcre (8.45-r2)
(6/29) Installing apache2 (2.4.53-r0)
Executing apache2-2.4.53-r0.pre-install
(7/29) Installing libbz2 (1.0.8-r1)
(8/29) Installing libffi (3.4.2-r1)
(9/29) Installing gdbm (1.23-r0)
(10/29) Installing xz-libs (5.2.5-r1)
(11/29) Installing libgcc (11.2.1_git20220219-r2)
(12/29) Installing libstdc++ (11.2.1_git20220219-r2)
(13/29) Installing mpdecimal (2.5.1-r1)
(14/29) Installing sqlite-libs (3.38.5-r0)
(15/29) Installing python3 (3.10.4-r0)
(16/29) Installing apache2-mod-wsgi (4.9.0-r0)
(17/29) Installing openssl (1.1.1o-r0)
(18/29) Installing apache2-ssl (2.4.53-r0)
Executing apache2-ssl-2.4.53-r0.post-install
(19/29) Installing apache2-utils (2.4.53-r0)
(20/29) Installing pkgconf (1.8.0-r0)
(21/29) Installing zlib-dev (1.2.12-r1)
(22/29) Installing xz-dev (5.2.5-r1)
(23/29) Installing libxml2 (2.9.14-r0)
(24/29) Installing libxml2-dev (2.9.14-r0)
(25/29) Installing php81-common (8.1.6-r1)
(26/29) Installing argon2-libs (20190702-r1)
(27/29) Installing libedit (20210910.3.1-r0)
(28/29) Installing pcre2 (10.39-r0)
(29/29) Installing php81-apache2 (8.1.6-r1)
Executing busybox-1.35.0-r13.trigger
OK: 103 MiB in 55 packages
Removing intermediate container 35a12f7fd1fd
 ---> e09786b515ed
Step 6/24 : RUN apk --no-cache add php81 php81-dev php81-fpm php81-mysqli php81-opcache php81-gd zlib php81-curl php81-phar php81-mbstring php81-pecl-mcrypt php81-zip php81-pdo php81-pdo_mysql php81-iconv php81-dom php81-session php81-intl php81-soap php81-fileinfo php81-xml php81-ctype
 ---> Running in 62f1fb6be424
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:

  php81-pecl-mcrypt (no such package):
    required by: world[php81-pecl-mcrypt]
Removing intermediate container 62f1fb6be424
```

**Comment by FaserF** [comment]
fixed with the newest 2.4.0 release. Seems like alpine 3.16 changed quite a lot. Should have done some more testing before releasing it :)

Please give it now another try, please use "Check for updates" in the Add-On Store before doing so
![image](https://user-images.githubusercontent.com/12374134/172566058-1af8a59f-6432-43b8-809d-646589fdea9f.png)
